language: python
python:
  - "3.9"

services:
  - docker

before_install:
  - touch .env
  - echo SECRET_KEY=$SECRET_KEY >> .env
  - echo DATABASE_URL=$DATABASE_URL >> .env
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script: pip install docker-compose

script: 
  - docker-compose run app sh -c "python manage.py test && flake8"